version: '2'

services:
  app-service:
    build:
      context: .
    ports:
    - "8080:8080"

  db:
    image: library/postgres:alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: S@ng29031998
    ports:
      - "5432:5432"

  cache-redis:
    image: library/redis:alpine
    restart: always
    container_name: redis-cache
    ports:
      - "6379:6379"